
[functions.update-ia]
enabled = true
verify_jwt = false
import_map = "./functions/update-ia/deno.json"
entrypoint = "./functions/update-ia/index.ts"

[functions.update-prices]
enabled = true
verify_jwt = true
import_map = "./functions/update-prices/deno.json"
entrypoint = "./functions/update-prices/index.ts"

[functions.update-trades]
enabled = true
verify_jwt = false
import_map = "./functions/update-trades/deno.json"
entrypoint = "./functions/update-trades/index.ts"

# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/update-prices/*.html" ]
